# Generated by Django 3.2 on 2021-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emailNotice',
            field=models.BooleanField(default=True),
        ),
    ]
